import {nanoid} from 'nanoid';
import {DEFAULT_LOCALE} from '../../countries';
import {setShowTrailingZeroKeyValue} from '../../app/lib/utils';

const initialBorderValues = {
  cornerRadius: 8,
  opacity: 100,
  thickness: 1,
};
const initialShadowValues = {
  blur: 0,
  horizontalOffset: 0,
  opacity: 0,
  verticalOffset: 0,
};

export const initialSingletonsValues = {
  home: {
    sections: [
      {
        _key: nanoid(),
        _type: 'richtextSection',
        contentAlignment: 'center',
        desktopContentPosition: 'center',
        maxWidth: 450,
        richtext: [
          {
            _key: nanoid(),
            _type: 'block',
            children: [
              {
                _key: nanoid(),
                _type: 'span',
                text: 'Welcome aboard!',
                marks: [],
              },
            ],
            markDefs: [],
            style: 'h1',
          },
          {
            _key: nanoid(),
            _type: 'block',
            children: [
              {
                _key: nanoid(),
                _type: 'span',
                marks: [],
                text: "Let's start by adding some content. You can toggle Sanity preview mode with the keyboard shortcut ",
              },
              {
                _key: nanoid(),
                _type: 'span',
                marks: ['strong'],
                text: 'cmd + ctrl + p',
              },
              {
                _key: nanoid(),
                _type: 'span',
                marks: [],
                text: ', or navigate to ',
              },
              {
                _key: nanoid(),
                _type: 'span',
                marks: ['em'],
                text: '/sanity/preview',
              },
              {
                _key: nanoid(),
                _type: 'span',
                marks: [],
                text: '.',
              },
            ],
            markDefs: [],
            style: 'normal',
          },
        ],
        settings: {
          _type: 'sectionSettings',
          hide: false,
          padding: {
            _type: 'padding',
            bottom: 80,
            top: 80,
          },
        },
      },
    ],
  },
  typography: {
    heading: {
      baseSize: 50,
      lineHeight: 1.2,
      letterSpacing: 0,
    },
    body: {
      baseSize: 16,
      lineHeight: 1.2,
      letterSpacing: 0,
    },
    extra: {
      baseSize: 16,
      lineHeight: 1.2,
      letterSpacing: 0,
    },
  },
  settings: {
    siteName: 'Fluid',
    grid: {
      horizontalSpace: 20,
      verticalSpace: 20,
    },
    badgesCornerRadius: 50,
    badgesPosition: 'bottom_left',
    badgesSaleColorScheme: {
      _ref: 'sale-badge-color-scheme',
      _type: 'reference',
    },
    badgesSoldOutColorScheme: {
      _ref: 'sold-out-badge-color-scheme',
      _type: 'reference',
    },
    buttonsBorder: initialBorderValues,
    buttonsShadow: initialShadowValues,
    blogCards: {
      border: {
        cornerRadius: 8,
        opacity: 100,
        thickness: 0,
      },
      shadow: initialShadowValues,
      style: 'standard',
      textAlignment: 'left',
    },
    collectionCards: {
      border: {
        cornerRadius: 8,
        opacity: 100,
        thickness: 0,
      },
      shadow: initialShadowValues,
      style: 'standard',
      textAlignment: 'left',
    },
    dropdownsAndPopupsBorder: initialBorderValues,
    dropdownsAndPopupsShadow: initialShadowValues,
    inputsBorder: initialBorderValues,
    inputsShadow: initialShadowValues,
    mediaBorder: {
      cornerRadius: 8,
      opacity: 100,
      thickness: 0,
    },
    mediaShadow: initialShadowValues,
    productCards: {
      border: {
        cornerRadius: 8,
        opacity: 100,
        thickness: 0,
      },
      shadow: initialShadowValues,
      style: 'standard',
      textAlignment: 'left',
    },
    showCurrencyCodes: true,
    showTrailingZeros: false,
    facebook: 'https://facebook.com/shopify',
    instagram: 'https://instagram.com/shopify',
    linkedin: 'https://linkedin.com/company/shopify',
    pinterest: 'https://pinterest.com/shopify',
    snapchat: 'https://snapchat.com/add/shopify',
    tiktok: 'https://tiktok.com/@shopify',
    tumblr: 'https://shopify.tumblr.com',
    twitter: 'https://twitter.com/shopify',
    vimeo: 'https://vimeo.com/shopify',
    youtube: 'https://www.youtube.com/shopify',
  },
  header: {
    showSeparatorLine: true,
    sticky: 'onScrollUp',
    desktopLogoWidth: 90,
    blur: true,
    padding: {
      _type: 'padding',
      top: 10,
      bottom: 10,
    },
    annoucementBar: [
      {
        _key: nanoid(),
        _type: 'announcement',
        externalLink: 'https://github.com/frontvibe/fluid',
        openInNewTab: true,
        text: '🐙 Give us a star ⭐️',
      },
    ],
    annoucementBarColorScheme: {
      _ref: 'dark-color-scheme',
      _type: 'reference',
    },
    menu: [
      {
        _key: nanoid(),
        _type: 'internalLink',
        link: {
          _ref: 'collections-page',
          _type: 'reference',
        },
        name: 'Collections',
      },
      {
        _key: nanoid(),
        _type: 'internalLink',
        link: {
          _ref: 'products-page',
          _type: 'reference',
        },
        name: 'Products',
      },
    ],
  },
  footer: {
    footers: [
      {
        _key: nanoid(),
        _type: 'socialLinksOnly',
        copyright: '© 2024 Fluid, Inc. All rights reserved.',
        settings: {
          _type: 'sectionSettings',
          colorScheme: {
            _ref: 'dark-color-scheme',
            _type: 'reference',
          },
          hide: false,
          padding: {
            _type: 'padding',
            bottom: 100,
            top: 100,
          },
        },
      },
    ],
  },
  themeContent: {
    account: {
      welcome: 'Welcome, {firstName}.',
      welcomeToYourAccount: 'Welcome to your account',
      accountDetails: 'Account details',
      signOut: 'Sign out',
      orderHistory: 'Order history',
      noOrdersMessage: "You haven't placed any orders yet.",
      startShopping: 'Start shopping',
      orderDetail: 'Order detail',
      returnToAccount: 'Return to account',
      orderNumber: 'Order number',
      placedOn: 'Placed on',
      product: 'Product',
      price: 'Price',
      quantity: 'Quantity',
      total: 'Total',
      subtotal: 'Subtotal',
      discounts: 'Discounts',
      discountsOff: '-{discount}% OFF',
      tax: 'Tax',
      shippingAddress: 'Shipping address',
      noShippingAddress: 'No shipping address',
      status: 'Status',
      updateYourProfile: 'Update your profile',
      firstName: 'First name',
      lastName: 'Last name',
      company: 'Company',
      addressLine1: 'Address line 1',
      addressLine2: 'Address line 2',
      city: 'City',
      stateProvince: 'State / Province (zoneCode)',
      postalCode: 'Zip / Postal Code',
      country: 'Country',
      phone: 'Phone',
      defaultAddress: 'Default address',
      saving: 'Saving',
      save: 'Save',
      cancel: 'Cancel',
      addName: 'Add name',
      addAddress: 'Add address',
      editAddress: 'Edit address',
      addressBook: 'Address book',
      noAddress: 'No address',
      default: 'Default',
      edit: 'Edit',
      remove: 'Remove',
      profile: 'Profile',
      name: 'Name',
      phoneNumber: 'Phone number',
      emailAddress: 'Email address',
      orderId: 'Order ID',
      orderDate: 'Order date',
      fulfillmentStatus: 'Fulfillment status',
      viewDetails: 'View details',
      orderStatusCancelled: 'Cancelled',
      orderStatusError: 'Error',
      orderStatusFailure: 'Failure',
      orderStatusOpen: 'Open',
      orderStatusPending: 'Pending',
      orderStatusSuccess: 'Success',
    },
    cart: {
      applyDiscount: 'Apply discount',
      discountCode: 'Discount code',
      discounts: 'Discount(s)',
      orderSummary: 'Order summary',
      proceedToCheckout: 'Continue to checkout',
      quantity: 'Quantity',
      remove: 'Remove',
      subtotal: 'Subtotal',
      heading: 'Your Cart',
      continueShopping: 'Continue shopping',
      emptyMessage:
        "Looks like you haven't added anything yet, let's get you started!",
    },
    collection: {
      apply: 'Apply',
      clear: 'Clear',
      clearFilters: 'Clear all filters',
      filterAndSort: 'Filter and sort',
      loadMoreProducts: 'Load more products',
      loadPrevious: 'Load previous',
      loading: 'Loading...',
      filterInStock: 'In stock',
      filterOutOfStock: 'Out of stock',
      noProductFound: 'No product found',
      noCollectionFound: 'No collection found',
      from: 'From',
      to: 'To',
      sortBestSelling: 'Best selling',
      sortBy: 'Sort by:',
      sortFeatured: 'Featured',
      sortHighLow: 'Price: High - Low',
      sortLowHigh: 'Price: Low - High',
      sortNewest: 'Newest',
      viewAll: 'View all',
    },
    error: {
      pageNotFound: 'Page not found',
      reloadPage: 'Reload page',
      sectionError: 'An error occurred while loading this section.',
      serverError: 'An error occurred',
      missingAddressId: 'You must provide an address id.',
      addressCreation: 'Expected customer address to be created.',
    },
    product: {
      addToCart: 'Add to cart',
      quantitySelector: 'Quantity selector',
      sale: 'Sale',
      soldOut: 'Sold out',
    },
  },
} as const;
